#!/bin/bash

lvstorage=/dev/storage/EncryptedStorage
encryptedstorage=/dev/mapper/enc_encrypted_storage
mounted=/encrypted_storage

start(){
    if [ -n "$(sudo lvdisplay |awk '/Status.+NOT/{print $NF}')" ]; then
        sudo lvchange -ay $(echo $lvstorage|sed 's/\/dev\///')
    fi

    if [ -n "$(sudo lvdisplay |awk '/Status/{print $NF}')" ]; then
        if [ -L $lvstorage ]&&[ ! -L $encryptedstorage ]; then
            sudo cryptsetup luksOpen $lvstorage $(basename $encryptedstorage)
        fi

    else
        echo "LV Status check fail! have a LV ?"
        exit 1
    fi
    
    if [ -L $encryptedstorage ]; then
        sudo mount $mounted
        sudo chgrp adm $mounted
        sudo chmod g+w $mounted
    else
        echo "Create the encrypted storage fail!"
        return 1
    fi
}

stop(){
    if [ -L $encryptedstorage ]; then
        sudo umount $mounted
        sudo cryptsetup luksClose $(basename $encryptedstorage)
		return $?;
    fi
}

exportstorage(){
	vgname=storage
	if [ -n "$(sudo vgchange -an storage|awk '/ 0 logical volume.+'$vgname'.+ active$/')" ]; then
		if [ -n "$(sudo vgexport storage|awk '/'$vgname'.+successfully exported$/')" ]; then
			if [ -z "$(sudo vgdisplay -v|awk '/'$vgname'.+exported$/')" ]; then
				echo "Successfully exported."; return 0;
			else
				echo "Export maybe fail!"; return 1;
			fi
		else
			echo "Export maybe fail! because find not about the success information."; return 1;
		fi
	else
		echo "May be cannot deactive the VG. you need manual to trouble-shooting!"; return 1;
	fi
}

importstorage(){
	vgname="$(sudo pvscan -v|awk '/PV.+\/dev\/.+exported VG /{print $7}')"
	if [ -n "$vgname" ]; then
		sudo vgimport $vgname 2>&1 >/dev/null
		if [ -n "$(sudo vgdisplay -v|awk '/VG Status\s+resizable$/')" ]; then
			echo "Successfully imported."
			if [ -n "$(sudo vgchange -ay $vgname|awk '/ 1 logical volume.+'$vgname'.+ now active/')" ]; then
				echo "The VG $vgname is in active."; return 0;
			else
				echo "Active the VG $vgname fail!"; return 1;
			fi
		else
			echo "Import maybe fail!"; return 1;
		fi
	else
		echo "Find not any exported VG volume(s)!"; return 1;
	fi
}

case "$1" in
    start|stop) "$1" ;;
	exportstorage) 
		stop
		[ $? -eq 0 ] && "$1"
		;;
	importstorage)
		"$1"
		[ $? -eq 0 ] && start
		;;
esac

